version: "3"
services:
  # postgres:
  #   image: postgres:latest
  #   restart: always
  #   # volumes:
  #   #   - ./data/postgres:/var/lib/postgresql/data
  #   environment:
  #     - PGDATA=/var/lib/postgresql/data/pgdata
  #     - POSTGRES_PASSWORD=password
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_DB=thingsboard
  mytb:
    restart: always
    image: "thingsboard/tb-postgres"
    ports:
      - "8080:9090"
      - "1883:1883"
    environment:
      TB_QUEUE_TYPE: in-memory
    # volumes:
    #   - ./.data/mytb-data:/data
    #   - ./.data/mytb-logs:/var/log/thingsboard
    #   - ./logback.xml:/usr/share/thingsboard/conf/logback.xml
